<template>
  <uni-popup ref="popup" type="dialog" :isMaskClick="false">
    <uni-popup-dialog
      ref="inputDialog"
      mode="input"
      title="学员姓名设置"
      placeholder="请输入学生的真实姓名"
      :value="studentName"
      @confirm="confirmName"
      @close="closeDialog"
      :focus="false"
      :closeOnClickOverlay="false"
      :showClose="false"
    ></uni-popup-dialog>
  </uni-popup>
</template>

<script>
export default {
  name: 'StudentNameModal',
  data() {
    return {
      studentName: ''
    }
  },
  methods: {
    // 打开弹窗
    open() {
      try {
        console.log('开始检查是否需要设置学生姓名')
        // 从本地获取用户信息
        let userInfo = uni.getStorageSync('userInfo')
        
        // 确保userInfo是对象
        if (typeof userInfo === 'string') {
          try {
            userInfo = JSON.parse(userInfo)
          } catch (e) {
            console.log('解析userInfo字符串失败，尝试获取另一个存储的用户信息')
            userInfo = null
          }
        }
        
        // 如果用户信息为空，尝试获取uni-id-pages-userInfo
        if (!userInfo) {
          userInfo = uni.getStorageSync('uni-id-pages-userInfo')
          console.log('从uni-id-pages-userInfo获取用户信息', userInfo ? '成功' : '失败')
        }
        
        // 如果没有用户信息，则不显示弹窗
        if (!userInfo) {
          console.log('用户未登录，不显示设置弹窗')
          return
        }
        
        // 检查用户是否有昵称
        if (!userInfo.nickname && !userInfo.nickName) {
          console.log('用户没有昵称，不显示设置弹窗')
          return
        }
        
        const nickname = userInfo.nickname || userInfo.nickName
        
        // 检查用户是否已设置过姓名标记
        const hasSetStudentName = uni.getStorageSync('hasSetStudentName') === true || uni.getStorageSync('hasSetStudentName') === 'true'
        
        // 检查用户是否有真实姓名
        const hasRealName = userInfo.real_name && userInfo.real_name.trim() !== ''
        
        // 检查昵称是否为系统生成的临时昵称
        const isAutoGeneratedNickname = 
          nickname.startsWith('用户') || 
          nickname === '微信用户' ||
          /^用户\d+$/.test(nickname)
        
        console.log('当前昵称:', nickname, 
                    isAutoGeneratedNickname ? '(自动生成的昵称)' : '(非自动生成)',
                    '已设置姓名标记:', hasSetStudentName ? '是' : '否',
                    '有真实姓名:', hasRealName ? '是' : '否')
        
        // 如果用户已有真实姓名或已设置过姓名标记且昵称不是自动生成的，不显示弹窗
        if (hasRealName) {
          console.log('用户已有真实姓名，不显示弹窗')
          // 确保设置标记
          if (!hasSetStudentName) {
            uni.setStorageSync('hasSetStudentName', true)
          }
          return
        }
        
        if (hasSetStudentName && !isAutoGeneratedNickname) {
          console.log('用户已设置姓名且昵称不是自动生成的，不显示弹窗')
          return
        }
        
        // 如果是自动生成的昵称，才需要显示弹窗
        if (isAutoGeneratedNickname) {
          console.log('检测到自动生成的昵称，清除设置标记，确保弹出设置弹窗')
          uni.removeStorageSync('hasSetStudentName')
          // 显示弹窗
          this.showNameDialog()
        } else {
          // 如果没有明确标记但昵称不是自动生成的，认为已设置
          console.log('昵称不是自动生成的，可能是真实姓名，设置标记并跳过')
          uni.setStorageSync('hasSetStudentName', true)
          return
        }
      } catch (e) {
        console.error('打开姓名设置弹窗错误:', e)
      }
    },
    
    // 显示姓名设置弹窗
    showNameDialog() {
      // 强制显示弹窗
      console.log('需要设置学生姓名，显示设置弹窗')
      
      // 确保弹窗已加载完成
      this.$nextTick(() => {
        if (this.$refs.popup) {
          this.$refs.popup.open()
        } else {
          console.error('弹窗组件未找到')
        }
      })
    },
    
    // 关闭弹窗
    close() {
      console.log('student-name-modal关闭弹窗')
      if (this.$refs.popup) {
        this.$refs.popup.close()
      }
    },
    
    // 确认姓名
    confirmName(name) {
      console.log('学生姓名确认:', name)
      if (!name || name.trim() === '') {
        uni.showToast({
          title: '姓名不能为空',
          icon: 'none'
        })
        
        // 姓名为空时不关闭弹窗，继续等待输入
        return
      }
      
      // 更新用户昵称到云数据库
      this.updateUserNickname(name)
    },
    
    // 用户取消设置姓名 - 禁用了取消按钮，但保留此方法以防意外调用
    closeDialog() {
      console.log('用户试图取消设置姓名，但此操作被禁止')
      // 提示用户必须设置姓名
      uni.showToast({
        title: '请输入学生真实姓名',
        icon: 'none'
      })
      
      // 不执行任何关闭操作，保持弹窗打开状态
      return
    },
    
    // 更新用户昵称到云数据库
    async updateUserNickname(name, isTemporary = false) {
      try {
        uni.showLoading({
          title: '保存中...',
          mask: true
        })
        
        console.log('准备更新用户昵称:', name, isTemporary ? '(临时姓名)' : '(正式姓名)')
        
        if (!name || name.trim() === '') {
          throw new Error('姓名不能为空')
        }
        
        // 获取token并传递给云函数
        const token = uni.getStorageSync('uni_id_token')
        if (!token) {
          throw new Error('未登录，请重新登录')
        }
        
        // 获取用户ID
        const userInfo = uni.getStorageSync('uni-id-pages-userInfo') || {}
        const userId = userInfo._id || userInfo.uid || userInfo.userId || ''
        
        console.log('传递token给云函数:', token.substring(0, 10) + '...')
        if (userId) {
          console.log('传递用户ID:', userId)
        }
        
        // 使用多种方式进行更新，如果一种失败，尝试另一种
        let success = false
        
        // 如果是临时姓名并且不需要发送到服务器，则只更新本地存储
        if (isTemporary) {
          console.log('设置临时姓名，仅更新本地存储')
          success = true
        } else {
          // 方法1: 使用自定义云函数
          try {
            console.log('方法1: 使用自定义云函数更新昵称')
            const result = await uniCloud.callFunction({
              name: 'updateUserInfo',
              data: {
                nickname: name,
                nickName: name,
                token: token,
                uni_id_token: token,
                userId: userId,
                uid: userId,
                _id: userId,
                mobile: userInfo.mobile || userInfo.phoneNumber || '',
                isRealName: true, // 标记这是真实姓名
                real_name: name   // 同时设置real_name字段
              }
            })
            
            console.log('方法1结果:', result)
            
            if (result.result && result.result.code === 0) {
              success = true
              
              // 保存服务器返回的新token（如果有）
              if (result.result.token) {
                console.log('保存服务器返回的新token')
                uni.setStorageSync('uni_id_token', result.result.token)
                
                // 同时更新token过期时间
                if (result.result.tokenExpired) {
                  uni.setStorageSync('uni_id_token_expired', result.result.tokenExpired)
                }
              }
              
              // 更新用户信息
              if (result.result.data) {
                console.log('更新本地用户信息')
                uni.setStorageSync('uni-id-pages-userInfo', result.result.data)
                uni.setStorageSync('userInfo', result.result.data)
              }
            }
          } catch (e) {
            console.error('方法1失败:', e)
          }
          
          // 如果方法1失败，尝试方法2
          if (!success) {
            try {
              console.log('方法2: 使用uni-id-co更新昵称')
              const uniIdCo = uniCloud.importObject('uni-id-co', { customUI: true })
              const res = await uniIdCo.updateUser({ 
                nickname: name,
                real_name: name // 同时更新真实姓名字段
              })
              
              console.log('方法2结果:', res)
              
              if (res.errCode === 0) {
                success = true
                
                // 保存服务器返回的新token（如果有）
                if (res.token) {
                  console.log('保存服务器返回的新token')
                  uni.setStorageSync('uni_id_token', res.token)
                  
                  // 同时更新token过期时间
                  if (res.tokenExpired) {
                    uni.setStorageSync('uni_id_token_expired', res.tokenExpired)
                  }
                }
                
                // 更新用户信息
                if (res.userInfo) {
                  console.log('更新本地用户信息')
                  uni.setStorageSync('uni-id-pages-userInfo', res.userInfo)
                  uni.setStorageSync('userInfo', res.userInfo)
                }
              }
            } catch (e) {
              console.error('方法2失败:', e)
            }
          }
        }
        
        // 无论云端是否更新成功，都更新本地存储
        // 更新本地存储
        let storedUserInfo = uni.getStorageSync('uni-id-pages-userInfo') || {}
        storedUserInfo.nickname = name
        storedUserInfo.nickName = name 
        storedUserInfo.real_name = name // 同时更新real_name字段
        uni.setStorageSync('uni-id-pages-userInfo', storedUserInfo)
        
        // 同时更新自定义存储
        uni.setStorageSync('userInfo', storedUserInfo)
        
        // 确保token是有效的
        const currentToken = uni.getStorageSync('uni_id_token')
        if (!currentToken) {
          console.warn('设置姓名后发现token丢失，尝试恢复登录状态')
          // 触发重新登录事件
          uni.$emit('check:login')
        }
        
        // 触发用户信息更新事件
        uni.$emit('user:updated', storedUserInfo)
        
        if (!isTemporary) {
          uni.showToast({
            title: success ? '保存成功' : '本地保存成功',
            icon: 'success'
          })
          
          // 只有非临时姓名才记录已设置姓名
          uni.setStorageSync('hasSetStudentName', true)
        } else {
          // 对于临时姓名，确保下次登录时仍然弹出设置框
          uni.removeStorageSync('hasSetStudentName')
        }
        
        // 关闭弹窗前，确保用户登录状态稳定
        setTimeout(() => {
          // 在保存完成后触发刷新用户界面
          uni.$emit('refresh:user-info')
          
          // 关闭弹窗
          this.close()
          
          // 等待弹窗完全关闭后刷新页面
          setTimeout(() => {
            // 触发页面刷新
            uni.$emit('page:refresh');
            
            // 尝试重新加载页面数据
            const currentPage = getCurrentPages()[getCurrentPages().length - 1];
            if (currentPage && currentPage.$vm && typeof currentPage.$vm.refreshPage === 'function') {
              console.log('调用页面的refreshPage方法');
              currentPage.$vm.refreshPage();
            }
          }, 300);
        }, 500)
      } catch (error) {
        console.error('更新用户昵称失败:', error)
        uni.showToast({
          title: '保存失败: ' + (error.message || '未知错误'),
          icon: 'none'
        })
      } finally {
        uni.hideLoading()
      }
    }
  },
  mounted() {
    // 不需要额外设置maskClick，因为我们已经通过props直接设置了isMaskClick=false
  }
}
</script>

<style>
</style> 