<template>
  <uni-popup ref="popup" type="dialog">
    <uni-popup-dialog
      ref="inputDialog"
      mode="input"
      title="学员姓名设置"
      placeholder="请输入您的真实姓名"
      :value="studentName"
      @confirm="confirmName"
      @close="closeDialog"
      :focus="false"
    ></uni-popup-dialog>
  </uni-popup>
</template>

<script>
export default {
  name: 'StudentNameModal',
  data() {
    return {
      studentName: ''
    }
  },
  methods: {
    // 打开弹窗
    open() {
      try {
        console.log('开始检查是否需要设置学生姓名')

        // 检查用户是否已登录
        const userInfo = uni.getStorageSync('uni-id-pages-userInfo')
        if (!userInfo) {
          console.log('用户未登录，无需显示姓名设置弹窗')
          return
        }

        // 更全面地检查是否有自动生成的昵称
        // 1. 以"用户"开头 2. 为"微信用户" 3. 含有默认昵称的关键词
        const nickname = userInfo.nickname || ''
        const isAutoGeneratedNickname = (
          nickname.startsWith('用户') || 
          nickname === '微信用户' ||
          nickname.includes('默认昵称') ||
          /^用户\d+$/.test(nickname) // 匹配"用户"后跟数字的模式
        )
        
        console.log('当前昵称:', nickname || '无昵称', 
                    isAutoGeneratedNickname ? '(自动生成的昵称)' : '')

        // 检查用户是否已设置过姓名标记
        const hasSetStudentName = uni.getStorageSync('hasSetStudentName')
        
        // 如果是自动生成的昵称，无论hasSetStudentName标记如何，都清除并显示弹窗
        if (isAutoGeneratedNickname) {
          console.log('检测到自动生成的昵称，清除设置标记，确保弹出设置弹窗')
          uni.removeStorageSync('hasSetStudentName')
        } else if (hasSetStudentName) {
          // 非自动生成昵称且已设置过，无需再次设置
          console.log('用户已设置过学生姓名，无需再次设置')
          return
        }
        
        // 如果没有昵称或是自动生成的昵称，显示弹窗
        if (!nickname || isAutoGeneratedNickname || !hasSetStudentName) {
          console.log('需要设置学生姓名，显示设置弹窗')
          
          // 确保弹窗已加载完成
          this.$nextTick(() => {
            if (this.$refs.popup) {
              this.$refs.popup.open()
            } else {
              console.error('弹窗组件未找到')
            }
          })
        }
      } catch (e) {
        console.error('打开姓名设置弹窗错误:', e)
      }
    },
    
    // 关闭弹窗
    close() {
      console.log('student-name-modal关闭弹窗')
      if (this.$refs.popup) {
        this.$refs.popup.close()
      }
    },
    
    // 确认姓名
    confirmName(name) {
      console.log('学生姓名确认:', name)
      if (!name || name.trim() === '') {
        uni.showToast({
          title: '姓名不能为空',
          icon: 'none'
        })
        return
      }
      
      // 更新用户昵称到云数据库
      this.updateUserNickname(name)
    },
    
    // 用户取消设置姓名
    closeDialog() {
      console.log('用户取消设置姓名')
      // 无论是否第一次设置姓名，都清除标记，确保下次仍弹出
      uni.removeStorageSync('hasSetStudentName')
      console.log('清除姓名设置标记，确保下次登录时仍弹出设置窗口')
      
      // 生成临时姓名
      const tempName = '用户' + Math.floor(Math.random() * 1000000)
      console.log('生成临时姓名:', tempName)
      // 更新临时姓名到本地存储，但不标记为已设置
      this.updateUserNickname(tempName, true)
    },
    
    // 更新用户昵称到云数据库
    async updateUserNickname(name, isTemporary = false) {
      try {
        uni.showLoading({
          title: '保存中...',
          mask: true
        })
        
        console.log('准备更新用户昵称:', name, isTemporary ? '(临时姓名)' : '(正式姓名)')
        
        if (!name || name.trim() === '') {
          throw new Error('姓名不能为空')
        }
        
        // 获取token并传递给云函数
        const token = uni.getStorageSync('uni_id_token')
        if (!token) {
          throw new Error('未登录，请重新登录')
        }
        
        // 获取用户ID
        const userInfo = uni.getStorageSync('uni-id-pages-userInfo') || {}
        const userId = userInfo._id || userInfo.uid || userInfo.userId || ''
        
        console.log('传递token给云函数:', token.substring(0, 10) + '...')
        if (userId) {
          console.log('传递用户ID:', userId)
        }
        
        // 使用多种方式进行更新，如果一种失败，尝试另一种
        let success = false
        
        // 如果是临时姓名并且不需要发送到服务器，则只更新本地存储
        if (isTemporary) {
          console.log('设置临时姓名，仅更新本地存储')
          success = true
        } else {
          // 方法1: 使用自定义云函数
          try {
            console.log('方法1: 使用自定义云函数更新昵称')
            const result = await uniCloud.callFunction({
              name: 'updateUserInfo',
              data: {
                nickname: name,
                nickName: name,
                token: token,
                uni_id_token: token,
                userId: userId,
                uid: userId,
                _id: userId,
                mobile: userInfo.mobile || userInfo.phoneNumber || ''
              }
            })
            
            console.log('方法1结果:', result)
            
            if (result.result && result.result.code === 0) {
              success = true
            }
          } catch (e) {
            console.error('方法1失败:', e)
          }
          
          // 如果方法1失败，尝试方法2
          if (!success) {
            try {
              console.log('方法2: 使用uni-id-co更新昵称')
              const uniIdCo = uniCloud.importObject('uni-id-co', { customUI: true })
              const res = await uniIdCo.updateUser({ nickname: name })
              
              console.log('方法2结果:', res)
              
              if (res.errCode === 0) {
                success = true
              }
            } catch (e) {
              console.error('方法2失败:', e)
            }
          }
        }
        
        // 无论云端是否更新成功，都更新本地存储
        // 更新本地存储
        let storedUserInfo = uni.getStorageSync('uni-id-pages-userInfo') || {}
        storedUserInfo.nickname = name
        storedUserInfo.nickName = name 
        uni.setStorageSync('uni-id-pages-userInfo', storedUserInfo)
        
        // 同时更新自定义存储
        uni.setStorageSync('userInfo', storedUserInfo)
        
        // 触发用户信息更新事件
        uni.$emit('user:updated', storedUserInfo)
        
        if (!isTemporary) {
          uni.showToast({
            title: success ? '保存成功' : '本地保存成功',
            icon: 'success'
          })
          
          // 只有非临时姓名才记录已设置姓名
          uni.setStorageSync('hasSetStudentName', true)
        } else {
          // 对于临时姓名，确保下次登录时仍然弹出设置框
          uni.removeStorageSync('hasSetStudentName')
        }
        
        // 关闭弹窗
        this.close()
      } catch (error) {
        console.error('更新用户昵称失败:', error)
        uni.showToast({
          title: '保存失败: ' + (error.message || '未知错误'),
          icon: 'none'
        })
      } finally {
        uni.hideLoading()
      }
    }
  }
}
</script>

<style>
</style> 